### Found
GET http://localhost:8001/api/v1/query?id=1
Accept: application/json

### Not Found
GET http://localhost:8001/api/v1/query?id=9001
Accept: application/json

###
GET http://localhost:8001/api/v1/search?imdbId=tt0292644
Accept: application/json

###
GET http://localhost:8001/api/v1/search?imdbId=tt0101452
Accept: application/json

###
GET http://localhost:8001/pre-cache
Accept: application/json

###
GET http://localhost:8001/api/v1/check-pre-cache
Accept: application/json

###
GET http://localhost:8001/api/v1/pre-cache-missing
Accept: application/json

### deprecated
GET http://localhost:8001/api/v1/data/q
Accept: application/json